# Castlevania: Circle of the Moon
version=2
transform=none
writable=1
selector=fixed,8,0x0,0x3d0
checksum=byte_sum,0x19,u8,0x10,0x3e0
field=en:Mode|zh:模式,u16,0x9C,0,65535,1
field=en:Playtime Frames|zh:游戏时间帧,u32,0xA0,0,4294967295,60
field=en:Location|zh:位置,be16,0xA4,0,65535,1
field=en:Warp Room 1|zh:传送房1,u8,0xA6,0,1,1,0,1
field=en:Warp Room 2|zh:传送房2,u8,0xA7,0,1,1,0,1
field=en:Warp Room 3|zh:传送房3,u8,0xA8,0,1,1,0,1
field=en:Warp Room 4|zh:传送房4,u8,0xA9,0,1,1,0,1
field=en:Warp Room 5|zh:传送房5,u8,0xAA,0,1,1,0,1
field=en:Level|zh:等级,u8,0x30C,1,99,1
field=en:Experience|zh:经验,u32,0x310,0,99999999,1
field=en:HP|zh:体力,u16,0x2D6,1,9999,1
field=en:MP|zh:魔力,u16,0x2DE,0,9999,1
field=en:Hearts|zh:心数,u16,0x2E4,0,999,1
field=en:Subweapon|zh:副武器,u8,0x2E8,0,255,1
