# Final Fight One
version=2
transform=reverse8
writable=1
selector=latest,1,0x0,0x100,2,0x0,none,0x0,u16
checksum=word_sub,0xfe,u16,0x0,0x100
slot_label=en:Save Count|zh:保存次数,u16,0x0,1
field=en:Opponents Defeated|zh:击败敌人,u16,0x2,0,9999,1
field=en:Pending Stage|zh:待继续关卡,u8,0x6B,0,5,1
field=en:Continues|zh:续关,u8,0x6C,1,9,1
field=en:Character|zh:角色,u8,0x6D,0,255,1
field=en:Player|zh:玩家,u8,0x6E,1,9,1
field=en:1st Character|zh:第1名角色,u8,0x12,0,255,1
field=en:1st Color|zh:第1名颜色,u8,0x13,0,3,1
field=en:2nd Character|zh:第2名角色,u8,0x22,0,255,1
field=en:2nd Color|zh:第2名颜色,u8,0x23,0,3,1
