# F-Zero: Maximum Velocity
version=2
transform=none
writable=1
selector=fixed,3,0x48c0,0x330
valid=0x4010,selected_bit,absolute
checksum=word_sum,0x4008,u32,0x4010,0x48b0,absolute
checksum=word_nonzero,0x400c,u32,0x4010,0x48b0,absolute
checksum=word_sum,0x0,u32,0x8,0x328,slot_header8
checksum=word_nonzero,0x4,u32,0x8,0x328,slot_header8
checksum=word_sparse5,0x7658,u32,0x4008,0x524c,absolute
checksum=word_sparse5,0x765c,u32,0x400c,0x5250,absolute
field=en:Championship Clears|zh:冠军赛通关,u8,0x1E,0,255,1
field=en:Unlocked Machines|zh:解锁赛车数,u8,0x7,0,5,1,0,5
field=en:Jet Vermilion|zh:Jet Vermilion,u8,0x7,0,1,1,5,1
field=en:Queen Class|zh:Queen级,u8,0x7,0,1,1,6,1
field=en:Championship|zh:冠军赛,u8,0x7,0,1,1,7,1
field=en:Pawn Circuit 1|zh:Pawn赛道1,u8,0x8,0,1,1,0,1
field=en:Pawn Circuit 2|zh:Pawn赛道2,u8,0x8,0,1,1,1,1
field=en:Pawn Circuit 3|zh:Pawn赛道3,u8,0x8,0,1,1,2,1
field=en:Pawn Circuit 4|zh:Pawn赛道4,u8,0x8,0,1,1,3,1
field=en:Spare Machines|zh:备用赛车,u8,0x6,0,7,1,4,3
field=en:Controller|zh:控制器,u8,0x6,0,15,1,0,4
field=en:Music|zh:音乐,u8,0x6,0,1,1,7,1
