# Kuru Kuru Kururin
version=2
transform=none
writable=1
selector=active_section,5,0x0,0x2254,0x10,0x0,0x1f4,1|2|3|4|0
valid=0x1A,nonzero
checksum=byte_sum,0x12,u16,0x18,0x226b,section
checksum=byte_sum,0x14,u16,0x226c,0x44c0,section
slot_label=en:Name|zh:名字,string,0x1A,8
field=en:Rank|zh:等级,u8,0x25,0,255,1
field=en:Difficulty|zh:难度,u8,0x28,0,1,1,4,1
field=en:Last Land|zh:最后大陆,u8,0x28,0,1,1,1,1
field=en:Challenge 11|zh:挑战11,u8,0x28,0,1,1,2,1
field=en:Equipped Part|zh:装备部件,u8,0x30,0,255,1
field=en:Equipped Paint|zh:装备涂装,u8,0x31,0,255,1
field=en:Chikurin|zh:Chikurin,u8,0x2C,0,1,1,0,1
field=en:Hoyorin|zh:Hoyorin,u8,0x2C,0,1,1,1,1
field=en:Gizarin|zh:Gizarin,u8,0x2C,0,1,1,2,1
