# Konami Krazy Racers
version=2
transform=none
writable=1
selector=fixed,3,0x3dc,0x110
checksum=byte_sum_xor,0x10c,u16,0x0,0x110
slot_label=en:Save Count|zh:保存次数,u16,0x80,1
field=en:Class|zh:级别,u8,0xA4,0,255,1
field=en:Title|zh:称号,u8,0xA8,0,255,1
field=en:Coins|zh:金币,u16,0xB0,0,999,1
field=en:Character|zh:角色,u8,0xAC,0,255,1
field=en:Krazy Cup|zh:疯狂杯,u8,0xA0,0,255,1
field=en:Hyper Cup|zh:超级杯,u8,0xA1,0,255,1
field=en:Premium Cup|zh:高级杯,u8,0xA2,0,255,1
field=en:Champion Cup|zh:冠军杯,u8,0xA3,0,255,1
field=en:Eye Wrap|zh:眼罩,u8,0xBE,0,2,1
field=en:Time Bomber|zh:定时炸弹,u8,0xBF,0,2,1
field=en:Barrier|zh:屏障,u8,0xC1,0,2,1
