# Sonic Advance
version=2
transform=none
writable=1
selector=last_magic,1,0x1000,0x1000,9,0x0,PIRO
checksum=word_sum,0x42c,u32,0x0,0x42c
field=en:Tails Progression|zh:Tails进度,u16,0xA,0,65535,1
field=en:Knuckles Progression|zh:Knuckles进度,u16,0xC,0,65535,1
field=en:Amy Progression|zh:Amy进度,u16,0xE,0,65535,1
field=en:Emerald Red|zh:红宝石,u8,0x1D,0,1,1,0,1
field=en:Emerald Blue|zh:蓝宝石,u8,0x1D,0,1,1,1,1
field=en:Emerald Yellow|zh:黄宝石,u8,0x1D,0,1,1,2,1
field=en:Emerald Green|zh:绿宝石,u8,0x1D,0,1,1,3,1
field=en:Emerald White|zh:白宝石,u8,0x1D,0,1,1,4,1
field=en:Emerald Cyan|zh:青宝石,u8,0x1D,0,1,1,5,1
field=en:Emerald Purple|zh:紫宝石,u8,0x1D,0,1,1,6,1
field=en:Total Wins|zh:胜场,u8,0x425,0,99,1
field=en:Total Losses|zh:败场,u8,0x426,0,99,1
