# Wario Land 4
version=2
transform=none
writable=1
selector=fixed,2,0x100,0x400
checksum=wario_sum,0x10,u32,0x0,0x1e0,0xffffffff,0x14
checksum=wario_complement,0x14,u32,0x0,0x1e0,0xffffffff,0x10
field=en:Difficulty|zh:难度,u8,0x18,0,2,1
field=en:Money Raw|zh:金钱原始值,u32,0x20,0,99999,1
field=en:Medals|zh:奖牌,u16,0x1C,0,999,1
field=en:Homerun Derby|zh:本垒打,u16,0x13C,0,999,1
field=en:Wario Hop|zh:跳跃,u16,0x13E,0,999,1
field=en:Roulette|zh:轮盘,u16,0x140,0,999,1
field=en:Entry Jewel 1|zh:入口宝石1,u8,0x24,0,1,1,0,1
field=en:Entry Jewel 2|zh:入口宝石2,u8,0x24,0,1,1,1,1
field=en:Entry Jewel 3|zh:入口宝石3,u8,0x24,0,1,1,2,1
field=en:Entry Jewel 4|zh:入口宝石4,u8,0x24,0,1,1,3,1
field=en:Keyzer|zh:钥匙怪,u8,0x24,0,1,1,5,1
