# Super Street Fighter II Turbo Revival
version=2
transform=reverse8
writable=1
selector=latest,1,0x0,0x100,2,0x0,none,0x8,u32
checksum=byte_sum_xor,0xf6,u8,0x0,0x100
slot_label=en:Save Count|zh:保存次数,u32,0x8,1
field=en:VS Point|zh:VS点数,u16,0x94,0,9999,1
field=en:Break Car T1|zh:砸车时间1,u8,0xA9,0,99,1
field=en:Break Car T2|zh:砸车时间2,u8,0xAA,0,99,1
field=en:Break Car T3|zh:砸车时间3,u8,0xAB,0,99,1
field=en:Barrel A T1|zh:木桶A时间1,u8,0xAD,0,99,1
field=en:Barrel A T2|zh:木桶A时间2,u8,0xAE,0,99,1
field=en:Barrel A T3|zh:木桶A时间3,u8,0xAF,0,99,1
field=en:Defeat 5 T1|zh:击败5人时间1,u8,0xB5,0,99,1
field=en:Defeat 10 T1|zh:击败10人时间1,u8,0xB9,0,99,1
