# WarioWare Inc.: Mega Microgame$! / Minigame Mania
version=2
transform=none
writable=1
selector=fixed,1,0x0,0x0
checksum=word_sum,0x8,u32,0x0,0x404
field=en:Gender|zh:性别,u8,0x1C,0,1,1
field=en:Language|zh:语言,u8,0x1FF,0,255,1
field=en:Game 0 Progress|zh:游戏0进度,u8,0x20,0,255,1
field=en:Game 0 Top 1|zh:游戏0记录1,u16,0x22,0,999,1
field=en:Game 0 Top 2|zh:游戏0记录2,u16,0x24,0,999,1
field=en:Game 0 Top 3|zh:游戏0记录3,u16,0x26,0,999,1
field=en:Game 1 Progress|zh:游戏1进度,u8,0x28,0,255,1
field=en:Game 1 Top 1|zh:游戏1记录1,u16,0x2A,0,999,1
field=en:Grid 0 Progress|zh:网格0进度,u8,0x100,0,255,1
field=en:Grid 0 High Score|zh:网格0高分,u16,0x200,0,999,1
field=en:Introduction|zh:介绍,u8,0x400,0,1,1,2,1
field=en:Jimmy Blue Intro|zh:Jimmy Blue介绍,u8,0x400,0,1,1,3,1
