# Sonic Advance 3
version=2
transform=none
writable=1
selector=latest,1,0x0,0x1000,16,0x0,LNTG,0x4,u32
checksum=word_sum,0x368,u32,0x0,0x368
slot_label=en:Save Count|zh:保存次数,u32,0x4,1
field=en:Sonic Unlocked|zh:Sonic解锁,u8,0x19,0,1,1,0,1
field=en:Cream Unlocked|zh:Cream解锁,u8,0x19,0,1,1,1,1
field=en:Tails Unlocked|zh:Tails解锁,u8,0x19,0,1,1,2,1
field=en:Knuckles Unlocked|zh:Knuckles解锁,u8,0x19,0,1,1,3,1
field=en:Amy Unlocked|zh:Amy解锁,u8,0x19,0,1,1,4,1
field=en:Sound Test|zh:声音测试,u8,0x3D,0,1,1,0,1
field=en:Boss Time Attack|zh:Boss计时,u8,0x3D,0,1,1,1,1
field=en:Secret Hint|zh:秘密提示,u8,0x3D,0,1,1,2,1
field=en:Special Keys|zh:特殊钥匙,u8,0x2C,0,9,1
field=en:Total Wins|zh:胜场,u8,0x64,0,99,1
field=en:Total Draws|zh:平局,u8,0x65,0,99,1
field=en:Total Losses|zh:败场,u8,0x66,0,99,1
